app = "controle-despesas-api-projetoweb"
primary_region = "gru"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "3000"
  DB_PATH = "/data/banco.db"

[mounts]
  source = "controle_despesas_data"
  destination = "/data"
  initial_size = "1gb"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0

  [[http_service.checks]]
    grace_period = "5s"
    interval = "30s"
    method = "GET"
    timeout = "5s"
    path = "/api/health"
